/*
Copyright (c) 2025 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdio.h>

#include <windows.h>
#include <d3d.h>

enum EXAMPLE_ENUM
{
    EXAMPLE_ENUM_ONE    = 1,
    EXAMPLE_ENUM_TWO    = 2,
    EXAMPLE_ENUM_THREE  = 3,
    EXAMPLE_ENUM_FOUR   = 4,
    EXAMPLE_ENUM_FIVE   = 5,
    EXAMPLE_ENUM_SIX    = 6
};

const int small_switch_example(enum EXAMPLE_ENUM input)
{
    switch (input)
    {
    case EXAMPLE_ENUM_ONE:
    case EXAMPLE_ENUM_TWO: return 20;
    case EXAMPLE_ENUM_FOUR: return 30;
    case EXAMPLE_ENUM_FIVE: return 50;
    default: return 70;
    }

    return -1;
}

const char* large_switch_example(HRESULT err)
{
    switch (err)
    {
    case D3D_OK:                                return "S_OK";
    case D3DERR_BADMAJORVERSION:				return "D3DERR_BADMAJORVERSION";
    case D3DERR_BADMINORVERSION:				return "D3DERR_BADMINORVERSION";
    case D3DERR_INVALID_DEVICE:					return "D3DERR_INVALID_DEVICE";
    case D3DERR_INITFAILED:						return "D3DERR_INITFAILED";
	case D3DERR_DEVICEAGGREGATED:				return "D3DERR_DEVICEAGGREGATED";
	case D3DERR_EXECUTE_CREATE_FAILED:			return "D3DERR_EXECUTE_CREATE_FAILED";
	case D3DERR_EXECUTE_DESTROY_FAILED:			return "D3DERR_EXECUTE_DESTROY_FAILED";
	case D3DERR_EXECUTE_LOCK_FAILED:			return "D3DERR_EXECUTE_LOCK_FAILED";
	case D3DERR_EXECUTE_UNLOCK_FAILED:			return "D3DERR_EXECUTE_UNLOCK_FAILED";
	case D3DERR_EXECUTE_LOCKED:					return "D3DERR_EXECUTE_LOCKED";
	case D3DERR_EXECUTE_NOT_LOCKED:				return "D3DERR_EXECUTE_NOT_LOCKED";
	case D3DERR_EXECUTE_FAILED:					return "D3DERR_EXECUTE_FAILED";
	case D3DERR_EXECUTE_CLIPPED_FAILED:			return "D3DERR_EXECUTE_CLIPPED_FAILED";
	case D3DERR_TEXTURE_NO_SUPPORT:				return "D3DERR_TEXTURE_NO_SUPPORT";
	case D3DERR_TEXTURE_CREATE_FAILED:			return "D3DERR_TEXTURE_CREATE_FAILED";
	case D3DERR_TEXTURE_DESTROY_FAILED:			return "D3DERR_TEXTURE_DESTROY_FAILED";
	case D3DERR_TEXTURE_LOCK_FAILED:			return "D3DERR_TEXTURE_LOCK_FAILED";
	case D3DERR_TEXTURE_UNLOCK_FAILED:			return "D3DERR_TEXTURE_UNLOCK_FAILED";
	case D3DERR_TEXTURE_LOAD_FAILED:			return "D3DERR_TEXTURE_LOAD_FAILED";
	case D3DERR_TEXTURE_SWAP_FAILED:			return "D3DERR_TEXTURE_SWAP_FAILED";
	case D3DERR_TEXTURE_LOCKED:					return "D3DERR_TEXTURE_LOCKED";
	case D3DERR_TEXTURE_NOT_LOCKED:				return "D3DERR_TEXTURE_NOT_LOCKED";
	case D3DERR_TEXTURE_GETSURF_FAILED:			return "D3DERR_TEXTURE_GETSURF_FAILED";
	case D3DERR_MATRIX_CREATE_FAILED:			return "D3DERR_MATRIX_CREATE_FAILED";
	case D3DERR_MATRIX_DESTROY_FAILED:			return "D3DERR_MATRIX_DESTROY_FAILED";
	case D3DERR_MATRIX_SETDATA_FAILED:			return "D3DERR_MATRIX_SETDATA_FAILED";
	case D3DERR_MATRIX_GETDATA_FAILED:			return "D3DERR_MATRIX_GETDATA_FAILED";
	case D3DERR_SETVIEWPORTDATA_FAILED:			return "D3DERR_SETVIEWPORTDATA_FAILED";
	case D3DERR_INVALIDCURRENTVIEWPORT:			return "D3DERR_INVALIDCURRENTVIEWPORT";
	case D3DERR_INVALIDPRIMITIVETYPE:			return "D3DERR_INVALIDPRIMITIVETYPE";
	case D3DERR_INVALIDVERTEXTYPE:				return "D3DERR_INVALIDVERTEXTYPE";
	case D3DERR_TEXTURE_BADSIZE:				return "D3DERR_TEXTURE_BADSIZE";
	case D3DERR_INVALIDRAMPTEXTURE:				return "D3DERR_INVALIDRAMPTEXTURE";
	case D3DERR_MATERIAL_CREATE_FAILED:			return "D3DERR_MATERIAL_CREATE_FAILED";
	case D3DERR_MATERIAL_DESTROY_FAILED:		return "D3DERR_MATERIAL_DESTROY_FAILED";
	case D3DERR_MATERIAL_SETDATA_FAILED:		return "D3DERR_MATERIAL_SETDATA_FAILED";
	case D3DERR_MATERIAL_GETDATA_FAILED:		return "D3DERR_MATERIAL_GETDATA_FAILED";
	case D3DERR_INVALIDPALETTE:					return "D3DERR_INVALIDPALETTE";
	case D3DERR_ZBUFF_NEEDS_SYSTEMMEMORY:		return "D3DERR_ZBUFF_NEEDS_SYSTEMMEMORY";
	case D3DERR_ZBUFF_NEEDS_VIDEOMEMORY:		return "D3DERR_ZBUFF_NEEDS_VIDEOMEMORY";
	case D3DERR_SURFACENOTINVIDMEM:				return "D3DERR_SURFACENOTINVIDMEM";
	case D3DERR_LIGHT_SET_FAILED:				return "D3DERR_LIGHT_SET_FAILED";
	case D3DERR_LIGHTHASVIEWPORT:				return "D3DERR_LIGHTHASVIEWPORT";
	case D3DERR_LIGHTNOTINTHISVIEWPORT:			return "D3DERR_LIGHTNOTINTHISVIEWPORT";
	case D3DERR_SCENE_IN_SCENE:					return "D3DERR_SCENE_IN_SCENE";
	case D3DERR_SCENE_NOT_IN_SCENE:				return "D3DERR_SCENE_NOT_IN_SCENE";
	case D3DERR_SCENE_BEGIN_FAILED:				return "D3DERR_SCENE_BEGIN_FAILED";
	case D3DERR_SCENE_END_FAILED:				return "D3DERR_SCENE_END_FAILED";
	case D3DERR_INBEGIN:						return "D3DERR_INBEGIN";
	case D3DERR_NOTINBEGIN:						return "D3DERR_NOTINBEGIN";
	case D3DERR_NOVIEWPORTS:					return "D3DERR_NOVIEWPORTS";
	case D3DERR_VIEWPORTDATANOTSET:				return "D3DERR_VIEWPORTDATANOTSET";
	case D3DERR_VIEWPORTHASNODEVICE:			return "D3DERR_VIEWPORTHASNODEVICE";
	case D3DERR_NOCURRENTVIEWPORT:				return "D3DERR_NOCURRENTVIEWPORT";
    }

    return "<UNKNOWN>";
}

int main(int argc, char** argv)
{
    printf("%d\n", small_switch_example(EXAMPLE_ENUM_ONE));
    printf("%d\n", small_switch_example(EXAMPLE_ENUM_FOUR));
    printf("%s\n", large_switch_example(D3DERR_LIGHT_SET_FAILED));
    printf("%s\n", large_switch_example(D3DERR_TEXTURE_CREATE_FAILED));

    return 0;
}